import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Resolve directory names in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Import application data
import { categories } from './src/data/categories';
import { calculators } from './src/data/calculators';
import { blogArticles } from './src/data/blog';
import { guides } from './src/data/guides';
import { programmaticSEOPages } from './src/data/programmaticSEO';

const BASE_URL = 'https://moneymetrichubs.com';
const DIST_DIR = path.join(__dirname, 'dist');
const TEMPLATE_PATH = path.join(DIST_DIR, 'index.html');

if (!fs.existsSync(TEMPLATE_PATH)) {
  console.error(`Error: Build template not found at ${TEMPLATE_PATH}. Please run 'npm run build' first.`);
  process.exit(1);
}

// Read the index.html template generated by Vite
const template = fs.readFileSync(TEMPLATE_PATH, 'utf-8');

// Helper to convert basic Markdown to semantic HTML for guides
function markdownToHtml(md: string): string {
  let html = md.trim();

  // Convert headings
  html = html.replace(/^### (.*$)/gim, '<h3 class="font-display text-lg font-bold text-slate-900 dark:text-white pt-5 pb-2">$1</h3>');
  html = html.replace(/^## (.*$)/gim, '<h2 class="font-display text-xl font-bold text-slate-900 dark:text-white pt-6 pb-2">$1</h2>');
  html = html.replace(/^# (.*$)/gim, '<h1 class="font-display text-2xl font-extrabold text-slate-900 dark:text-white pt-8 pb-3">$1</h1>');

  // Convert lists
  // Unordered lists
  html = html.replace(/^\* (.*$)/gim, '<li class="text-sm text-slate-600 dark:text-slate-350 py-1 leading-relaxed">$1</li>');
  // Wrap list items in <ul> if needed (simplified block-level wrapping)
  
  // Convert Bold markdown
  html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');

  // Convert equations (e.g. $$A = P...$$)
  html = html.replace(/\$\$(.*?)\$\$/g, '<div class="my-5 p-4 bg-slate-100 dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 font-mono text-center text-sm text-slate-800 dark:text-slate-200 overflow-x-auto">$1</div>');
  html = html.replace(/\$(.*?)\$/g, '<code class="px-1.5 py-0.5 bg-slate-100 dark:bg-slate-800 rounded font-mono text-xs">$1</code>');

  // Convert double newlines to paragraphs
  const paragraphs = html.split(/\n\s*\n/);
  const formattedParagraphs = paragraphs.map(p => {
    p = p.trim();
    if (!p) return '';
    if (p.startsWith('<h') || p.startsWith('<li') || p.startsWith('<div')) {
      return p;
    }
    // If it contains list items, wrap them in <ul>
    if (p.startsWith('<li')) {
      return `<ul class="list-disc pl-5 my-3 space-y-1">${p}</ul>`;
    }
    return `<p class="text-sm sm:text-base text-slate-600 dark:text-slate-300 leading-relaxed mb-4">${p}</p>`;
  });

  return formattedParagraphs.filter(Boolean).join('\n');
}

// Helper to generate dynamic JSON-LD schemas
function generateSchema(type: string, route: string, title: string, description: string, extra: any = {}): string {
  const schemas: any[] = [
    {
      '@context': 'https://schema.org',
      '@type': 'Organization',
      '@id': 'https://moneymetrichubs.com/#organization',
      'name': 'Money Metric Hubs',
      'url': 'https://moneymetrichubs.com',
      'logo': 'https://moneymetrichubs.com/logo.png',
      'description': 'Premium finance calculator platform for smart financial decisions.',
      'sameAs': [
        'https://twitter.com/moneymetricshub',
        'https://github.com/moneymetricshub'
      ]
    }
  ];

  if (type === 'home') {
    schemas.push({
      '@context': 'https://schema.org',
      '@type': 'WebSite',
      '@id': 'https://moneymetrichubs.com/#website',
      'url': 'https://moneymetrichubs.com',
      'name': 'Money Metric Hubs',
      'description': 'Smarter Financial Decisions Through Better Numbers',
      'potentialAction': {
        '@type': 'SearchAction',
        'target': 'https://moneymetrichubs.com/search?q={search_term_string}',
        'query-input': 'required name=search_term_string'
      }
    });
  } else if (type === 'calculator') {
    schemas.push({
      '@context': 'https://schema.org',
      '@type': 'WebApplication',
      '@id': `${BASE_URL}/${route}#webapp`,
      'name': title.split('|')[0].trim(),
      'url': `${BASE_URL}/${route}`,
      'applicationCategory': 'BusinessApplication',
      'operatingSystem': 'All',
      'browserRequirements': 'Requires JavaScript',
      'offers': {
        '@type': 'Offer',
        'price': '0',
        'priceCurrency': 'USD'
      }
    });

    schemas.push({
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      'itemListElement': [
        { '@type': 'ListItem', 'position': 1, 'name': 'Home', 'item': BASE_URL },
        { '@type': 'ListItem', 'position': 2, 'name': extra.categoryName || 'Calculators', 'item': `${BASE_URL}/categories/${extra.categorySlug || 'investing'}` },
        { '@type': 'ListItem', 'position': 3, 'name': title.split('|')[0].trim(), 'item': `${BASE_URL}/${route}` }
      ]
    });

    if (extra.faqs && extra.faqs.length > 0) {
      schemas.push({
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        'mainEntity': extra.faqs.map((faq: any) => ({
          '@type': 'Question',
          'name': faq.question,
          'acceptedAnswer': { '@type': 'Answer', 'text': faq.answer }
        }))
      });
    }
  } else if (type === 'article' || type === 'guide') {
    schemas.push({
      '@context': 'https://schema.org',
      '@type': 'Article',
      '@id': `${BASE_URL}/${route}#article`,
      'headline': title.split('|')[0].trim(),
      'description': description,
      'url': `${BASE_URL}/${route}`,
      'publisher': {
        '@type': 'Organization',
        'name': 'Money Metric Hubs',
        'logo': { '@type': 'ImageObject', 'url': 'https://moneymetrichubs.com/logo.png' }
      },
      'author': {
        '@type': 'Organization',
        'name': 'Money Metric Hubs Editorial Team'
      }
    });

    if (extra.faqs && extra.faqs.length > 0) {
      schemas.push({
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        'mainEntity': extra.faqs.map((faq: any) => ({
          '@type': 'Question',
          'name': faq.question,
          'acceptedAnswer': { '@type': 'Answer', 'text': faq.answer }
        }))
      });
    }
  }

  return schemas.map(schema => `<script type="application/ld+json" class="mmh-schema">${JSON.stringify(schema)}</script>`).join('\n  ');
}

// Header HTML Generator
function getHeaderHtml(activeRoute: string): string {
  const isCategories = activeRoute === 'categories';
  const isCompare = activeRoute === 'compare';
  const isBlog = activeRoute === 'blog';
  const isAbout = activeRoute === 'about';
  const isHome = activeRoute === '';

  return `
    <header class="sticky top-0 z-40 bg-white/90 dark:bg-slate-900/95 backdrop-blur-md border-b border-slate-100 dark:border-slate-800 shadow-sm transition-colors duration-200">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between items-center h-16 gap-4">
          <a href="/" class="flex items-center gap-2.5 cursor-pointer flex-shrink-0 decoration-none no-underline">
            <div class="w-9 h-9 rounded-xl bg-gradient-to-tr from-blue-600 to-emerald-500 text-white flex items-center justify-center font-bold text-lg shadow-sm">
              M
            </div>
            <div>
              <span class="font-display font-black text-lg tracking-tight text-slate-900 dark:text-white block leading-none">
                Money Metric <span class="text-blue-600 dark:text-blue-400">Hubs</span>
              </span>
              <span class="text-[9px] text-slate-400 dark:text-slate-500 font-bold uppercase tracking-widest mt-0.5 block leading-none">
                Precision Finance
              </span>
            </div>
          </a>

          <nav class="hidden lg:flex items-center gap-6">
            <a href="/" class="text-sm font-medium hover:text-blue-600 dark:hover:text-blue-400 transition-colors ${isHome ? 'text-blue-600 dark:text-blue-400 font-bold' : 'text-slate-600 dark:text-slate-300'}">Home</a>
            <a href="/categories" class="text-sm font-medium hover:text-blue-600 dark:hover:text-blue-400 transition-colors ${isCategories ? 'text-blue-600 dark:text-blue-400 font-bold' : 'text-slate-600 dark:text-slate-300'}">Categories</a>
            <a href="/compare" class="text-sm font-medium hover:text-blue-600 dark:hover:text-blue-400 transition-colors ${isCompare ? 'text-blue-600 dark:text-blue-400 font-bold' : 'text-slate-600 dark:text-slate-300'}">Compare Scenarios</a>
            <a href="/blog" class="text-sm font-medium hover:text-blue-600 dark:hover:text-blue-400 transition-colors ${isBlog ? 'text-blue-600 dark:text-blue-400 font-bold' : 'text-slate-600 dark:text-slate-300'}">Blog</a>
            <a href="/about" class="text-sm font-medium hover:text-blue-600 dark:hover:text-blue-400 transition-colors ${isAbout ? 'text-blue-600 dark:text-blue-400 font-bold' : 'text-slate-600 dark:text-slate-300'}">About</a>
          </nav>

          <div class="flex items-center gap-3">
            <a href="/preferences" class="p-2 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-full transition-all text-slate-500 dark:text-slate-400 hover:text-blue-600" title="My Hub & Favorites">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user-check"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><polyline points="16 11 18 13 22 9"/></svg>
            </a>
          </div>
        </div>
      </div>
    </header>
  `;
}

// Footer HTML Generator
function getFooterHtml(): string {
  return `
    <footer class="bg-slate-900 dark:bg-slate-950 text-slate-400 border-t border-slate-800 dark:border-slate-900 mt-16 pt-16 pb-8 transition-colors duration-200">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-12 gap-10">
          
          <div class="lg:col-span-4 space-y-4">
            <div class="flex items-center gap-2">
              <div class="w-8 h-8 rounded-lg bg-blue-600 text-white flex items-center justify-center font-bold text-base">M</div>
              <span class="font-display font-extrabold text-base tracking-tight text-white">
                Money Metric <span class="text-blue-400">Hubs</span>
              </span>
            </div>
            <p class="text-slate-400 text-xs sm:text-sm leading-relaxed max-w-sm">
              Smarter Financial Decisions Through Better Numbers. Instant calculations built entirely with verified formulas and variables.
            </p>
          </div>

          <div class="lg:col-span-3 space-y-4">
            <h4 class="text-xs font-bold text-slate-200 uppercase tracking-widest">Financial Fields</h4>
            <ul class="space-y-2 text-xs">
              ${categories.slice(0, 5).map(cat => `
                <li><a href="/categories/${cat.slug}" class="hover:text-white transition-colors decoration-none no-underline text-slate-400">${cat.name} Calculators</a></li>
              `).join('')}
            </ul>
          </div>

          <div class="lg:col-span-3 space-y-4">
            <h4 class="text-xs font-bold text-slate-200 uppercase tracking-widest">Trust & Legal</h4>
            <ul class="space-y-2 text-xs">
              <li><a href="/about" class="hover:text-white transition-colors decoration-none text-slate-400">About Our Methodology</a></li>
              <li><a href="/contact" class="hover:text-white transition-colors decoration-none text-slate-400">Contact & Feedback</a></li>
              <li><a href="/privacy" class="hover:text-white transition-colors decoration-none text-slate-400">Privacy Policy</a></li>
              <li><a href="/terms" class="hover:text-white transition-colors decoration-none text-slate-400">Terms of Service</a></li>
              <li><a href="/disclaimer" class="hover:text-white transition-colors decoration-none text-slate-400">Financial Disclaimer</a></li>
            </ul>
          </div>

          <div class="lg:col-span-2 space-y-4">
            <h4 class="text-xs font-bold text-slate-200 uppercase tracking-widest">Sitemaps & Tools</h4>
            <ul class="space-y-2 text-xs">
              <li><a href="/newsletter" class="hover:text-white transition-colors decoration-none text-slate-400">Newsletter Signup</a></li>
              <li><a href="/sitemap" class="hover:text-white transition-colors decoration-none text-slate-400">HTML Sitemap Index</a></li>
              <li><a href="/dashboard" class="hover:text-white transition-colors decoration-none text-slate-400">Search Console Metrics</a></li>
            </ul>
          </div>

        </div>

        <div class="border-t border-slate-800 mt-16 pt-8 space-y-4 text-center">
          <p class="text-[10px] text-slate-500 max-w-4xl mx-auto leading-relaxed">
            <strong>Disclaimer:</strong> Money Metric Hubs is an informational and educational publisher, not an investment, legal, or CPA advisor. The formulas, numbers, and calculators displayed here are estimations only. Past return metrics are not indicators of future yield curves. Always consult a professional before entering into binding loan contracts or committing capital.
          </p>
          <p class="text-[11px] text-slate-500 font-semibold tracking-wide">
            © 2026 Money Metric Hubs. All rights reserved. Built for complete mobile and search transparency.
          </p>
        </div>
      </div>
    </footer>
  `;
}

// Generate the complete prerendered body html for a given view content
function wrapInLayout(activeRoute: string, contentHtml: string): string {
  return `
    <div class="min-h-screen flex flex-col bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-100 transition-colors duration-200">
      ${getHeaderHtml(activeRoute)}
      <main class="flex-grow">
        ${contentHtml}
      </main>
      ${getFooterHtml()}
    </div>
  `;
}

// Master generator
function generatePage(route: string, title: string, description: string, schemaType: string, contentHtml: string, extraSchemaData: any = {}) {
  // Construct absolute file path
  let dirPath = DIST_DIR;
  let fileName = 'index.html';

  if (route !== '') {
    dirPath = path.join(DIST_DIR, route);
    // Create directory recursively
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
    }
  }

  const filePath = path.join(dirPath, fileName);

  // Parse layout active route key
  let activeRouteKey = '';
  if (route.startsWith('categories')) activeRouteKey = 'categories';
  else if (route.startsWith('blog')) activeRouteKey = 'blog';
  else if (route.startsWith('compare')) activeRouteKey = 'compare';
  else if (route.startsWith('about')) activeRouteKey = 'about';

  // Inject content and metadata into index.html template
  const completeBodyHtml = wrapInLayout(activeRouteKey, contentHtml);

  // Assemble dynamic head elements
  const canonicalTag = `<link rel="canonical" href="${BASE_URL}/${route}" />`;
  const schemaTags = generateSchema(schemaType, route, title, description, extraSchemaData);

  // Replace placeholders in Vite index.html template
  let pageHtml = template;

  // 1. Replace Title
  pageHtml = pageHtml.replace(/<title>.*?<\/title>/, `<title>${title}</title>`);

  // 2. Inject meta description or replace existing
  if (pageHtml.includes('name="description"')) {
    pageHtml = pageHtml.replace(/<meta name="description" content=".*?"\s*\/?>/, `<meta name="description" content="${description}" />`);
  } else {
    pageHtml = pageHtml.replace('</head>', `  <meta name="description" content="${description}" />\n</head>`);
  }

  // 3. Inject canonical and schemas in head
  const headAdditions = `\n  ${canonicalTag}\n  ${schemaTags}\n`;
  pageHtml = pageHtml.replace('</head>', `${headAdditions}</head>`);

  // 4. Inject content into <div id="root"></div>
  pageHtml = pageHtml.replace('<div id="root"></div>', `<div id="root">${completeBodyHtml}</div>`);

  // Write file out
  fs.writeFileSync(filePath, pageHtml, 'utf-8');
  console.log(`Prerendered: /${route} -> ${filePath}`);
}

console.log('--- STARTING BULLETPROOF PRERENDER FLOW ---');

// ==========================================
// 1. HOME PAGE
// ==========================================
const homeContent = `
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-12 animate-fade-in">
    <div class="text-center max-w-3xl mx-auto space-y-5">
      <span class="px-3.5 py-1.5 bg-blue-50 dark:bg-blue-950/40 text-blue-600 dark:text-blue-400 text-xs font-black tracking-widest uppercase rounded-full border border-blue-100/50 dark:border-blue-900/30">
        Precision Calculation Engines
      </span>
      <h1 class="font-display text-4xl sm:text-5xl font-extrabold text-slate-900 dark:text-white tracking-tight leading-tight">
        Smarter Financial Decisions <br class="hidden sm:inline" />
        Through <span class="bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-emerald-500">Better Numbers</span>
      </h1>
      <p class="text-sm sm:text-base text-slate-500 dark:text-slate-400 max-w-2xl mx-auto leading-relaxed">
        Eliminate guesswork. Access 20+ comprehensive financial calculators designed with mathematical precision, transparent variables, and interactive graphical projections.
      </p>
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 pt-6">
      ${categories.map(cat => `
        <div class="p-6 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl shadow-sm space-y-4">
          <div class="w-10 h-10 rounded-2xl bg-slate-50 dark:bg-slate-800 flex items-center justify-center text-blue-500 font-bold">
            ${cat.name[0]}
          </div>
          <h3 class="font-display font-bold text-base text-slate-900 dark:text-white">${cat.name}</h3>
          <p class="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">${cat.description}</p>
          <a href="/categories/${cat.slug}" class="text-xs font-bold text-blue-600 dark:text-blue-400 flex items-center gap-1.5 pt-2 hover:underline">
            Browse calculators &rarr;
          </a>
        </div>
      `).join('')}
    </div>

    <div class="border-t border-slate-100 dark:border-slate-800 pt-12 space-y-6">
      <h2 class="font-display text-2xl font-black text-slate-900 dark:text-white">Featured Financial Calculators</h2>
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        ${calculators.slice(0, 6).map(calc => `
          <div class="p-6 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl shadow-sm space-y-3 hover:border-slate-200 dark:hover:border-slate-700 transition-all">
            <span class="text-[10px] font-bold text-blue-600 uppercase tracking-widest">${calc.category.toUpperCase()}</span>
            <h3 class="font-display font-bold text-base text-slate-900 dark:text-white">${calc.name}</h3>
            <p class="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">${calc.shortDescription}</p>
            <a href="/calculators/${calc.slug}" class="text-xs font-bold text-blue-600 dark:text-blue-400 hover:underline block pt-2">
              Launch Calculator &rarr;
            </a>
          </div>
        `).join('')}
      </div>
    </div>

    <div class="border-t border-slate-100 dark:border-slate-800 pt-12 space-y-6">
      <h2 class="font-display text-2xl font-black text-slate-900 dark:text-white">Recent Articles & Guides</h2>
      <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
        ${blogArticles.slice(0, 3).map(article => `
          <div class="p-6 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl shadow-sm space-y-3">
            <span class="text-[10px] font-bold text-emerald-600 uppercase tracking-widest">${article.publishDate}</span>
            <h3 class="font-display font-bold text-sm text-slate-900 dark:text-white leading-snug">${article.title}</h3>
            <p class="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">${article.summary}</p>
            <a href="/blog/${article.slug}" class="text-xs font-bold text-blue-600 dark:text-blue-400 hover:underline block pt-2">
              Read Article &rarr;
            </a>
          </div>
        `).join('')}
      </div>
    </div>
  </div>
`;

generatePage('', 'Money Metric Hubs | Premium Financial Calculators', 'Grow your wealth and make smarter financial decisions with our 20+ free, precision-engineered financial calculators, interactive charts, and academic guides.', 'home', homeContent);

// ==========================================
// 2. CATEGORIES OVERVIEW PAGE
// ==========================================
const categoriesContent = `
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-8 animate-fade-in">
    <div class="border-b border-slate-100 dark:border-slate-800 pb-5">
      <h1 class="font-display text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">Calculator Channels</h1>
      <p class="text-slate-500 dark:text-slate-400 text-sm mt-1">Select a category below to access specialized mathematics and forecasting frameworks.</p>
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
      ${categories.map(cat => `
        <div class="p-6 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl shadow-sm space-y-3">
          <h2 class="font-display font-bold text-lg text-slate-900 dark:text-white">${cat.name}</h2>
          <p class="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">${cat.description}</p>
          <div class="pt-2">
            <a href="/categories/${cat.slug}" class="text-xs font-bold text-blue-600 dark:text-blue-400 hover:underline">
              Open Channel &rarr;
            </a>
          </div>
        </div>
      `).join('')}
    </div>
  </div>
`;

generatePage('categories', 'Financial Calculator Categories | Money Metric Hubs', 'Browse our extensive catalog of 20+ financial calculators organized into 8 categories: investing, loans, retirement, savings, income, debt, taxes, and business.', 'basic', categoriesContent);

// ==========================================
// 3. INDIVIDUAL CATEGORY PAGES
// ==========================================
categories.forEach(cat => {
  const catCalcs = calculators.filter(calc => calc.category === cat.id);
  const categoryContent = `
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-10 animate-fade-in">
      <div class="border-b border-slate-100 dark:border-slate-800 pb-6 space-y-2">
        <h1 class="font-display text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">${cat.name} Calculators</h1>
        <p class="text-slate-500 dark:text-slate-400 text-sm sm:text-base leading-relaxed">${cat.description}</p>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        ${catCalcs.length > 0 ? catCalcs.map(calc => `
          <div class="p-6 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl shadow-sm space-y-3 hover:border-slate-200 dark:hover:border-slate-700 transition-all">
            <h3 class="font-display font-bold text-base text-slate-900 dark:text-white">${calc.name}</h3>
            <p class="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">${calc.shortDescription}</p>
            <a href="/calculators/${calc.slug}" class="text-xs font-bold text-blue-600 dark:text-blue-400 hover:underline block pt-2">
              Launch Calculator &rarr;
            </a>
          </div>
        `).join('') : '<p class="text-xs text-slate-500 col-span-full">No calculators found in this category. More models are being programmed daily!</p>'}
      </div>

      <div class="p-6 sm:p-8 bg-blue-50/20 dark:bg-slate-900/40 rounded-3xl border border-slate-100 dark:border-slate-800 space-y-4">
        <h2 class="font-display text-lg font-bold text-slate-900 dark:text-white">Expert Insights: ${cat.name} Mathematics</h2>
        <p class="text-xs sm:text-sm text-slate-600 dark:text-slate-300 leading-relaxed">${cat.seoText}</p>
      </div>
    </div>
  `;

  generatePage(`categories/${cat.slug}`, `${cat.name} Calculators | Money Metric Hubs`, cat.description, 'basic', categoryContent);
});

// ==========================================
// 4. INDIVIDUAL CALCULATOR PAGES
// ==========================================
calculators.forEach(calc => {
  const categoryObject = categories.find(c => c.id === calc.category);
  const categoryName = categoryObject ? categoryObject.name : 'Calculators';

  const calculatorContent = `
    <div class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-10 animate-fade-in">
      <div class="border-b border-slate-100 dark:border-slate-800 pb-5 space-y-2">
        <span class="px-2.5 py-1 bg-blue-50 dark:bg-blue-950/40 text-blue-600 dark:text-blue-400 text-[10px] font-bold tracking-widest uppercase rounded">
          ${categoryName.toUpperCase()} CHANNEL
        </span>
        <h1 class="font-display text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">${calc.name}</h1>
        <p class="text-slate-500 dark:text-slate-400 text-sm leading-relaxed">${calc.shortDescription}</p>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-12 gap-8">
        <!-- Interactive Inputs placeholder for bots to index -->
        <div class="md:col-span-5 bg-white dark:bg-slate-900 p-6 rounded-3xl border border-slate-100 dark:border-slate-800 shadow-sm space-y-5">
          <h3 class="font-display font-bold text-sm text-slate-900 dark:text-white border-b border-slate-100 dark:border-slate-850 pb-2">Calculator Variables</h3>
          <form class="space-y-4" onsubmit="return false;">
            ${calc.inputs.map(input => `
              <div class="space-y-1">
                <label class="text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wide">${input.label}</label>
                <div class="relative">
                  ${input.prefix ? `<span class="absolute left-3 top-2.5 text-xs text-slate-400 font-bold">${input.prefix}</span>` : ''}
                  <input 
                    type="${input.type === 'number' ? 'number' : 'text'}" 
                    value="${input.defaultValue}" 
                    readonly
                    class="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-850 rounded-xl px-3 py-2.5 text-xs text-slate-700 dark:text-slate-300 outline-none ${input.prefix ? 'pl-7' : ''} ${input.suffix ? 'pr-10' : ''}"
                  />
                  ${input.suffix ? `<span class="absolute right-3 top-2.5 text-xs text-slate-400 font-bold">${input.suffix}</span>` : ''}
                </div>
              </div>
            `).join('')}
            <div class="pt-2">
              <button class="w-full py-3 bg-blue-600 text-white font-bold rounded-xl text-xs cursor-pointer shadow-sm">
                Calculate & Project
              </button>
            </div>
          </form>
        </div>

        <!-- Explanations, math formula, and definitions -->
        <div class="md:col-span-7 space-y-6">
          <div class="p-6 bg-slate-50 dark:bg-slate-900/50 rounded-3xl border border-slate-100 dark:border-slate-800 space-y-3">
            <h3 class="font-display font-bold text-sm text-slate-900 dark:text-white">Calculation Overview</h3>
            <p class="text-xs sm:text-sm text-slate-600 dark:text-slate-300 leading-relaxed">${calc.metaDescription}</p>
          </div>

          <!-- Formula Card -->
          <div class="p-6 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl shadow-sm space-y-4">
            <h3 class="font-display font-bold text-sm text-slate-900 dark:text-white flex items-center gap-1.5 text-blue-600 dark:text-blue-400 border-b border-slate-100 dark:border-slate-850 pb-2">
              Mathematical Model & Formula
            </h3>
            <div class="p-3 bg-slate-50 dark:bg-slate-950/80 rounded-xl border border-slate-100 dark:border-slate-850 text-center font-mono text-xs sm:text-sm font-bold text-slate-800 dark:text-slate-200 overflow-x-auto">
              ${calc.formula.equation}
            </div>
            <p class="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">${calc.formula.explanation}</p>
            
            <div class="space-y-2">
              <span class="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Variables Defined:</span>
              <ul class="space-y-1.5 text-xs text-slate-600 dark:text-slate-300 pl-3">
                ${calc.formula.variables.map(v => `
                  <li><strong>${v.name}:</strong> ${v.description}</li>
                `).join('')}
              </ul>
            </div>
          </div>
        </div>
      </div>

      <!-- Worked Example Step-by-Step -->
      <div class="p-6 sm:p-8 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl shadow-sm space-y-5">
        <h2 class="font-display text-lg font-bold text-slate-900 dark:text-white border-b border-slate-100 dark:border-slate-850 pb-2">Worked Example Scenario</h2>
        <div class="space-y-2 text-xs sm:text-sm">
          <p class="font-semibold text-slate-700 dark:text-slate-200">Scenario: ${calc.formula.example.scenario}</p>
          <ol class="list-decimal pl-5 space-y-1 text-slate-500 dark:text-slate-400">
            ${calc.formula.example.steps.map(step => `
              <li>${step}</li>
            `).join('')}
          </ol>
          <p class="font-bold text-emerald-600 dark:text-emerald-400 mt-2">Result: ${calc.formula.example.result}</p>
        </div>
      </div>

      <!-- FAQs Section -->
      ${calc.faqs && calc.faqs.length > 0 ? `
        <div class="p-6 sm:p-8 bg-slate-100/30 dark:bg-slate-900/20 border border-slate-100/50 dark:border-slate-850/30 rounded-3xl space-y-5">
          <h2 class="font-display text-lg font-bold text-slate-900 dark:text-white border-b border-slate-150 dark:border-slate-850 pb-2">Frequently Asked Questions</h2>
          <div class="space-y-4">
            ${calc.faqs.map(faq => `
              <div class="space-y-1.5">
                <h4 class="font-bold text-slate-900 dark:text-white text-sm">${faq.question}</h4>
                <p class="text-xs sm:text-sm text-slate-500 dark:text-slate-400 leading-relaxed">${faq.answer}</p>
              </div>
            `).join('')}
          </div>
        </div>
      ` : ''}

      <!-- References Section -->
      ${calc.references && calc.references.length > 0 ? `
        <div class="p-6 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl shadow-sm space-y-4">
          <h3 class="font-display font-bold text-sm text-slate-900 dark:text-white border-b border-slate-100 dark:border-slate-850 pb-2">Academic & Regulatory References</h3>
          <ul class="space-y-3.5 pl-1.5">
            ${calc.references.map(ref => `
              <li class="text-xs text-slate-500 dark:text-slate-400 space-y-1">
                <a href="${ref.url}" target="_blank" rel="noopener noreferrer" class="font-bold text-blue-600 dark:text-blue-400 hover:underline block">${ref.name} &rarr;</a>
                <span>${ref.description}</span>
              </li>
            `).join('')}
          </ul>
        </div>
      ` : ''}
    </div>
  `;

  generatePage(`calculators/${calc.slug}`, calc.title || `${calc.name} | Money Metric Hubs`, calc.metaDescription, 'calculator', calculatorContent, {
    categoryName: categoryName,
    categorySlug: calc.category,
    faqs: calc.faqs
  });
});

// ==========================================
// 5. BLOG OVERVIEW PAGE
// ==========================================
const blogContent = `
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-10 animate-fade-in">
    <div class="border-b border-slate-100 dark:border-slate-800 pb-5">
      <h1 class="font-display text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">Financial Math & Analysis Blog</h1>
      <p class="text-slate-500 dark:text-slate-400 text-sm mt-1">Deep dives into compound interest, mortgage physics, retirement timelines, and corporate pricing metrics.</p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
      ${blogArticles.map(article => `
        <div class="p-6 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl shadow-sm space-y-4 hover:border-slate-200 dark:hover:border-slate-700 transition-all">
          <div class="flex items-center justify-between text-[10px] font-bold text-slate-400">
            <span class="uppercase text-blue-600 dark:text-blue-400">${article.category}</span>
            <span>${article.publishDate}</span>
          </div>
          <h2 class="font-display font-bold text-lg text-slate-900 dark:text-white leading-snug">${article.title}</h2>
          <p class="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">${article.summary}</p>
          <div class="flex items-center justify-between pt-2 border-t border-slate-100 dark:border-slate-850 text-xs">
            <span class="text-slate-450">By ${article.author}</span>
            <a href="/blog/${article.slug}" class="font-bold text-blue-600 dark:text-blue-400 hover:underline">Read Article</a>
          </div>
        </div>
      `).join('')}
    </div>
  </div>
`;

generatePage('blog', 'Financial & Mathematics Blog | Money Metric Hubs', 'Read our comprehensive articles covering investing, loans, retirement, debt payoff, and business finance metrics.', 'basic', blogContent);

// ==========================================
// 6. INDIVIDUAL BLOG PAGES
// ==========================================
blogArticles.forEach(article => {
  const articleContent = `
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-8 animate-fade-in">
      <div class="space-y-4 pb-6 border-b border-slate-150 dark:border-slate-800">
        <div class="flex items-center gap-3.5 text-xs text-slate-400 font-bold">
          <span class="uppercase px-2.5 py-1 bg-blue-50 dark:bg-blue-950/40 text-blue-600 dark:text-blue-400 rounded">${article.category.toUpperCase()}</span>
          <span>${article.publishDate}</span>
          <span>&bull;</span>
          <span>${article.readTime}</span>
        </div>
        <h1 class="font-display text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight leading-snug">${article.title}</h1>
        <p class="text-slate-500 dark:text-slate-400 text-sm sm:text-base italic leading-relaxed">Written by ${article.author}</p>
      </div>

      <div class="prose dark:prose-invert max-w-none text-slate-700 dark:text-slate-300 text-sm sm:text-base leading-relaxed space-y-6">
        ${article.content}
      </div>

      <div class="pt-6 border-t border-slate-100 dark:border-slate-800 flex flex-wrap gap-2">
        ${article.tags.map(tag => `
          <span class="px-2.5 py-1 bg-slate-100 dark:bg-slate-850 text-slate-600 dark:text-slate-400 rounded-full text-xs font-semibold">#${tag}</span>
        `).join('')}
      </div>
    </div>
  `;

  generatePage(`blog/${article.slug}`, `${article.title} | Money Metric Hubs`, article.metaDescription, 'article', articleContent);
});

// ==========================================
// 7. WEALTH GUIDES PAGES
// ==========================================
guides.forEach(guide => {
  const guideContent = `
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-8 animate-fade-in">
      <div class="space-y-4 pb-6 border-b border-slate-150 dark:border-slate-800">
        <div class="flex items-center gap-3.5 text-xs text-slate-400 font-bold">
          <span class="uppercase px-2.5 py-1 bg-emerald-50 dark:bg-emerald-950/40 text-emerald-600 dark:text-emerald-400 rounded">${guide.category.toUpperCase()} GUIDE</span>
          <span>${guide.readTime}</span>
        </div>
        <h1 class="font-display text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight leading-snug">${guide.title}</h1>
        <p class="text-slate-500 dark:text-slate-400 text-sm sm:text-base leading-relaxed">${guide.summary}</p>
      </div>

      <div class="prose dark:prose-invert max-w-none text-slate-700 dark:text-slate-300 space-y-6">
        ${markdownToHtml(guide.content)}
      </div>

      ${guide.faqs && guide.faqs.length > 0 ? `
        <div class="p-6 sm:p-8 bg-slate-100/30 dark:bg-slate-900/20 border border-slate-100/50 dark:border-slate-850/30 rounded-3xl space-y-5 mt-10">
          <h2 class="font-display text-lg font-bold text-slate-900 dark:text-white border-b border-slate-150 dark:border-slate-850 pb-2">Frequently Asked Questions</h2>
          <div class="space-y-4">
            ${guide.faqs.map(faq => `
              <div class="space-y-1.5">
                <h4 class="font-bold text-slate-900 dark:text-white text-sm">${faq.question}</h4>
                <p class="text-xs sm:text-sm text-slate-500 dark:text-slate-400 leading-relaxed">${faq.answer}</p>
              </div>
            `).join('')}
          </div>
        </div>
      ` : ''}
    </div>
  `;

  generatePage(`guides/${guide.slug}`, `${guide.title} | Money Metric Hubs`, guide.metaDescription, 'guide', guideContent, { faqs: guide.faqs });
});

// ==========================================
// 8. PROGRAMMATIC SEO LONG-TAIL PAGES
// ==========================================
programmaticSEOPages.forEach(page => {
  const categorySlug = page.type === 'mortgage' ? 'loans' : page.type === 'compound-interest' ? 'investing' : page.type === 'retirement' || page.type === 'fire' ? 'retirement' : 'income';

  const seoContent = `
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-10 animate-fade-in">
      <div class="border-b border-slate-100 dark:border-slate-800 pb-5 space-y-2">
        <span class="text-xs text-blue-600 dark:text-blue-400 font-bold uppercase tracking-widest">${page.type.toUpperCase()} ANALYSIS</span>
        <h1 class="font-display text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">${page.h1}</h1>
        <p class="text-slate-500 dark:text-slate-400 text-sm sm:text-base leading-relaxed">${page.intro}</p>
      </div>

      <div class="space-y-8">
        <div class="bg-white dark:bg-slate-900 p-6 md:p-8 border border-slate-100 dark:border-slate-800 rounded-3xl shadow-sm space-y-3">
          <h2 class="font-display text-lg font-bold text-slate-900 dark:text-white">${page.section1Title}</h2>
          <p class="text-xs sm:text-sm text-slate-600 dark:text-slate-300 leading-relaxed">${page.section1Content}</p>
        </div>

        <div class="bg-white dark:bg-slate-900 p-6 md:p-8 border border-slate-100 dark:border-slate-800 rounded-3xl shadow-sm space-y-3">
          <h2 class="font-display text-lg font-bold text-slate-900 dark:text-white">${page.section2Title}</h2>
          <p class="text-xs sm:text-sm text-slate-600 dark:text-slate-300 leading-relaxed">${page.section2Content}</p>
        </div>
      </div>

      <div class="p-6 sm:p-8 bg-blue-50/20 dark:bg-slate-900/40 rounded-3xl border border-slate-100 dark:border-slate-850 space-y-4">
        <h3 class="font-display text-base font-bold text-slate-900 dark:text-white">Run the Calculation Online</h3>
        <p class="text-xs text-slate-500 dark:text-slate-400">This programmatic template links directly with our browser-only computation kernel. Click the link below to load this specific scenario's variables instantly:</p>
        <a href="/calculators/${page.calculatorId}" class="inline-flex items-center px-5 py-2.5 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-xl shadow-sm hover:no-underline transition-colors">
          Configure Online Solver &rarr;
        </a>
      </div>

      <!-- FAQ Section -->
      <div class="p-6 sm:p-8 bg-slate-100/30 dark:bg-slate-900/20 border border-slate-100/50 dark:border-slate-850/30 rounded-3xl space-y-5">
        <h2 class="font-display text-lg font-bold text-slate-900 dark:text-white border-b border-slate-150 dark:border-slate-850 pb-2">Frequently Asked Questions</h2>
        <div class="space-y-4">
          ${page.faqs.map(faq => `
            <div class="space-y-1.5">
              <h4 class="font-bold text-slate-900 dark:text-white text-sm">${faq.question}</h4>
              <p class="text-xs sm:text-sm text-slate-500 dark:text-slate-400 leading-relaxed">${faq.answer}</p>
            </div>
          `).join('')}
        </div>
      </div>

      <!-- References Section -->
      <div class="p-6 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl shadow-sm space-y-4">
        <h3 class="font-display font-bold text-sm text-slate-900 dark:text-white border-b border-slate-100 dark:border-slate-850 pb-2">Academic & Authority References</h3>
        <ul class="space-y-3 pl-1.5">
          ${page.references.map(ref => `
            <li class="text-xs text-slate-500 dark:text-slate-400 space-y-1">
              <a href="${ref.url}" target="_blank" rel="noopener noreferrer" class="font-bold text-blue-600 dark:text-blue-400 hover:underline block">${ref.name} &rarr;</a>
              <span>${ref.description}</span>
            </li>
          `).join('')}
        </ul>
      </div>

      <!-- Internal Navigation Links -->
      <div class="pt-6 border-t border-slate-100 dark:border-slate-800 space-y-3">
        <span class="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Related Calculations:</span>
        <div class="flex flex-wrap gap-3.5">
          ${page.internalLinks.map(link => `
            <a href="${link.url}" class="text-xs font-bold text-blue-600 dark:text-blue-400 hover:underline">${link.name} &rarr;</a>
          `).join('')}
        </div>
      </div>
    </div>
  `;

  // Route matches App.tsx: /mortgage/:slug or /compound-interest/:slug etc.
  const fullRoute = `${page.type}/${page.slug}`;
  generatePage(fullRoute, page.title, page.metaDescription, 'basic', seoContent, { faqs: page.faqs });
});

// ==========================================
// 9. LEGAL & CORE STANDALONE INFO PAGES
// ==========================================

// ABOUT
const aboutContent = `
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-8 text-slate-600 dark:text-slate-300">
    <div class="space-y-3 pb-4 border-b border-slate-100 dark:border-slate-800">
      <h1 class="font-display text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">About Money Metric Hubs</h1>
      <p class="text-slate-500 dark:text-slate-400 text-base">Mathematical accuracy combined with beautiful design.</p>
    </div>

    <div class="space-y-6 text-sm sm:text-base leading-relaxed">
      <p>
        Welcome to <strong>Money Metric Hubs</strong>. We are a premium financial technology platform designed to deliver clear, fast, and completely free calculations. We build our models to serve investors, home buyers, retirement planners, and savers.
      </p>

      <h3 class="font-display text-xl font-bold text-slate-950 dark:text-white pt-4">Our Mission</h3>
      <p>
        Our mission is summed up in our tagline: <strong>Smarter Financial Decisions Through Better Numbers</strong>. Many financial calculators on the web are either cluttered with aggressive ads or obfuscate their calculations behind confusing interfaces. We believe in complete variable transparency, academic formula explanations, and interactive visualizations.
      </p>

      <h3 class="font-display text-xl font-bold text-slate-950 dark:text-white pt-4">Core Principles</h3>
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
        <div class="p-5 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-xl space-y-2">
          <h4 class="font-bold text-slate-900 dark:text-white text-sm flex items-center gap-1.5 text-blue-600 dark:text-blue-400">Formula Transparency</h4>
          <p class="text-xs text-slate-500 dark:text-slate-400">Every calculator details the precise mathematical formula, variables, and limitations. No hidden equations.</p>
        </div>
        <div class="p-5 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-xl space-y-2">
          <h4 class="font-bold text-slate-900 dark:text-white text-sm flex items-center gap-1.5 text-emerald-600 dark:text-emerald-400">Verified References</h4>
          <p class="text-xs text-slate-500 dark:text-slate-400">Our math models cite official academic, governmental, and regulatory authorities like the IRS, SEC, and Federal Reserve.</p>
        </div>
      </div>

      <h3 class="font-display text-xl font-bold text-slate-950 dark:text-white pt-4">Editorial Integrity</h3>
      <p>
        MoneyMetricsHub maintains a strict distinction between editorial calculators and marketing partnerships. All tools are built entirely with verified formulas. We do not alter calculations to favor specific financial products or referrals.
      </p>
    </div>
  </div>
`;
generatePage('about', 'About Us | Money Metric Hubs', 'Learn about the mathematical methodology, academic principles, and financial guidelines driving Money Metric Hubs.', 'basic', aboutContent);

// CONTACT
const contactContent = `
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-8 text-slate-600 dark:text-slate-300">
    <div class="space-y-3 pb-4 border-b border-slate-100 dark:border-slate-800">
      <h1 class="font-display text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">Contact Us</h1>
      <p class="text-slate-500 dark:text-slate-400 text-base">We'd love to hear your feedback, calculator ideas, or partnership opportunities.</p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-12 gap-8 items-start">
      <div class="md:col-span-5 space-y-6">
        <div class="p-5 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-2xl shadow-sm space-y-4">
          <h3 class="font-display font-bold text-slate-900 dark:text-white text-base">Inquiries</h3>
          <div class="space-y-3 text-sm">
            <div>Email: <strong class="text-blue-600 dark:text-blue-400">support@moneymetrichubs.com</strong></div>
            <div>Location: <strong class="text-slate-700 dark:text-slate-200">San Francisco, CA</strong></div>
          </div>
        </div>
      </div>

      <div class="md:col-span-7 bg-white dark:bg-slate-900 p-6 md:p-8 rounded-3xl border border-slate-100 dark:border-slate-800 shadow-sm">
        <form class="space-y-4" onsubmit="return false;">
          <div class="space-y-1">
            <label class="text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wide">Name</label>
            <input type="text" placeholder="Your Name" class="w-full bg-slate-50 dark:bg-slate-950 border border-slate-250 dark:border-slate-800 px-4 py-2.5 rounded-xl text-sm" />
          </div>
          <div class="space-y-1">
            <label class="text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wide">Email</label>
            <input type="email" placeholder="you@example.com" class="w-full bg-slate-50 dark:bg-slate-950 border border-slate-250 dark:border-slate-800 px-4 py-2.5 rounded-xl text-sm" />
          </div>
          <div class="space-y-1">
            <label class="text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wide">Message</label>
            <textarea rows="4" placeholder="Your feedback..." class="w-full bg-slate-50 dark:bg-slate-950 border border-slate-250 dark:border-slate-800 px-4 py-2.5 rounded-xl text-sm"></textarea>
          </div>
          <button class="w-full bg-blue-600 text-white font-bold py-3 rounded-xl shadow-sm text-sm">Send Message</button>
        </form>
      </div>
    </div>
  </div>
`;
generatePage('contact', 'Contact Us | Money Metric Hubs', 'Have questions about our financial calculators? Reach out to the Money Metric Hubs editorial or engineering team.', 'basic', contactContent);

// PRIVACY POLICY
const privacyContent = `
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-6 text-slate-600 dark:text-slate-300 text-sm sm:text-base leading-relaxed">
    <div class="space-y-3 pb-4 border-b border-slate-100 dark:border-slate-800">
      <h1 class="font-display text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">Privacy Policy</h1>
      <p class="text-slate-500 dark:text-slate-400 text-sm">Last updated: June 2026</p>
    </div>

    <h3 class="font-display text-lg font-bold text-slate-950 dark:text-white pt-2">1. Browser-Only Calculations</h3>
    <p>
      At Money Metric Hubs, your personal financial data privacy is paramount. Unlike standard apps that upload portfolio metrics or loan details to secondary databases, all calculator engines on our platform execute entirely in your web browser. No personal income, loan, or investment figures are ever saved on our servers.
    </p>

    <h3 class="font-display text-lg font-bold text-slate-950 dark:text-white pt-2">2. Cookies, Advertising, and AdSense Disclosure</h3>
    <p>
      We utilize standard essential session cookies to analyze traffic patterns, speed up load times, and save user preferences (like your local currency or favorite calculators).
    </p>
    <p class="mt-2">
      We also partner with third-party vendors, including <strong>Google AdSense</strong>, to serve programmatic financial advertisements when you visit our website. These advertising partners use cookies to serve ads based on a user's prior visits to our website or other websites on the Internet.
    </p>

    <h3 class="font-display text-lg font-bold text-slate-950 dark:text-white pt-4">3. GDPR and CCPA Data Rights Compliance</h3>
    <p>
      Money Metric Hubs is fully committed to consumer data rights under regional laws such as the General Data Protection Regulation (GDPR) for European citizens and the California Consumer Privacy Act (CCPA) for California residents.
    </p>
  </div>
`;
generatePage('privacy', 'Privacy Policy | Money Metric Hubs', 'Learn how we protect your personal financial privacy. We perform calculations entirely in-browser and do not store inputted balances.', 'basic', privacyContent);

// TERMS OF SERVICE
const termsContent = `
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-6 text-slate-600 dark:text-slate-300 text-sm sm:text-base leading-relaxed">
    <div class="space-y-3 pb-4 border-b border-slate-100 dark:border-slate-800">
      <h1 class="font-display text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">Terms of Service</h1>
      <p class="text-slate-500 dark:text-slate-400 text-sm">Last updated: June 2026</p>
    </div>

    <h3 class="font-display text-lg font-bold text-slate-950 dark:text-white pt-2">1. Terms Acceptance</h3>
    <p>
      By accessing Money Metric Hubs, you agree to comply with and be bound by these terms. If you do not accept these policies, you must immediately cease usage of the calculators and site resources.
    </p>

    <h3 class="font-display text-lg font-bold text-slate-950 dark:text-white pt-2">2. Educational Purposes Only</h3>
    <p>
      All calculators, formulas, worked examples, and guides on this platform are designed purely for informational and educational purposes. Calculations do not constitute certified financial, legal, tax, or investment advising.
    </p>

    <h3 class="font-display text-lg font-bold text-slate-950 dark:text-white pt-2">3. Accuracy of Calculations</h3>
    <p>
      While we strive for absolute mathematical precision across our 20 calculators, we offer no warranties regarding the accuracy of output models under changing macroeconomic conditions or interest rate changes.
    </p>
  </div>
`;
generatePage('terms', 'Terms of Service | Money Metric Hubs', 'Standard terms of service and conditions for using the Money Metric Hubs website and calculators.', 'basic', termsContent);

// DISCLAIMER
const disclaimerContent = `
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-6 text-slate-600 dark:text-slate-300 text-sm sm:text-base leading-relaxed">
    <div class="space-y-3 pb-4 border-b border-slate-100 dark:border-slate-800">
      <h1 class="font-display text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">Financial Disclaimer</h1>
      <p class="text-slate-500 dark:text-slate-400 text-sm">Last updated: June 2026</p>
    </div>

    <div class="p-5 bg-amber-50 dark:bg-amber-950/20 text-amber-900 dark:text-amber-200 border border-amber-100 dark:border-amber-900/40 rounded-2xl flex gap-3.5 items-start text-xs sm:text-sm">
      <div class="space-y-2">
        <span class="font-bold uppercase block tracking-wider text-[11px] text-amber-800 dark:text-amber-400">Critical Notice</span>
        <p class="leading-relaxed">
          The calculations provided by Money Metric Hubs do not constitute financial advice. All formulas, values, interest compounding models, and guides are compiled for general education and estimation purposes only.
        </p>
      </div>
    </div>

    <h3 class="font-display text-lg font-bold text-slate-950 dark:text-white pt-2">Consult a Certified Professional</h3>
    <p>
      We strongly urge you to consult a certified financial planner (CFP), licensed CPA, legal advisor, or mortgage underwriter before making major life purchases (e.g. contracting a home loan) or investing large sums of cash. Individual risk profiles, tax considerations, and local jurisdiction rules can greatly alter real-world financial calculations.
    </p>
  </div>
`;
generatePage('disclaimer', 'Financial Disclaimer | Money Metric Hubs', 'The financial calculation disclaimer. All tools are informational. Consult a certified financial planner for personal decision-making.', 'basic', disclaimerContent);

// NEWSLETTER
const newsletterContent = `
  <div class="max-w-md mx-auto px-4 sm:px-6 py-16 text-center space-y-6 animate-fade-in">
    <h1 class="font-display text-2xl sm:text-3xl font-black text-slate-900 dark:text-white tracking-tight">Newsletter Briefing Signup</h1>
    <p class="text-xs sm:text-sm text-slate-500 dark:text-slate-400 leading-relaxed">Get our monthly mathematical finance breakdowns, custom planning models, and optimization frameworks delivered completely free.</p>
    
    <form class="space-y-3" onsubmit="return false;">
      <input type="email" placeholder="you@example.com" required class="w-full bg-white dark:bg-slate-950 border border-slate-200 dark:border-slate-800 px-4 py-3 rounded-xl text-xs sm:text-sm" />
      <button class="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 rounded-xl text-xs cursor-pointer shadow-sm">
        Subscribe to Briefing
      </button>
    </form>
  </div>
`;
generatePage('newsletter', 'Newsletter Briefing Signup | Money Metric Hubs', 'Subscribe to the Money Metric Hubs briefing to receive monthly calculators, financial math breakdowns, and productivity frameworks.', 'basic', newsletterContent);

// SITEMAP
const sitemapContent = `
  <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-10 animate-fade-in">
    <div class="border-b border-slate-150 dark:border-slate-800 pb-5">
      <h1 class="text-2xl sm:text-3xl font-display font-black tracking-tight text-slate-900 dark:text-white">HTML Sitemap Directory</h1>
      <p class="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-1">Complete structured index of all financial calculators, categories, articles, and programmatic scenarios.</p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
      <div class="space-y-4">
        <h2 class="text-sm font-bold text-slate-900 dark:text-white uppercase tracking-wider border-b pb-1.5">Core Pages</h2>
        <ul class="space-y-2 text-xs">
          <li><a href="/" class="text-blue-600 hover:underline">Homepage</a></li>
          <li><a href="/about" class="text-blue-600 hover:underline">About Our Methodology</a></li>
          <li><a href="/contact" class="text-blue-600 hover:underline">Contact & Feedback</a></li>
          <li><a href="/privacy" class="text-blue-600 hover:underline">Privacy Policy</a></li>
          <li><a href="/terms" class="text-blue-600 hover:underline">Terms of Service</a></li>
          <li><a href="/disclaimer" class="text-blue-600 hover:underline">Financial Disclaimer</a></li>
          <li><a href="/newsletter" class="text-blue-600 hover:underline">Newsletter Signup</a></li>
        </ul>
      </div>

      <div class="space-y-4">
        <h2 class="text-sm font-bold text-slate-900 dark:text-white uppercase tracking-wider border-b pb-1.5">Calculator Channels</h2>
        <ul class="space-y-2 text-xs">
          ${categories.map(cat => `
            <li><a href="/categories/${cat.slug}" class="text-blue-600 hover:underline font-bold">${cat.name}</a></li>
          `).join('')}
        </ul>
      </div>

      <div class="space-y-4">
        <h2 class="text-sm font-bold text-slate-900 dark:text-white uppercase tracking-wider border-b pb-1.5">Calculators</h2>
        <ul class="space-y-2 text-xs">
          ${calculators.map(calc => `
            <li><a href="/calculators/${calc.slug}" class="text-blue-600 hover:underline">${calc.name}</a></li>
          `).join('')}
        </ul>
      </div>
    </div>
  </div>
`;
generatePage('sitemap', 'HTML Sitemap Directory | Money Metric Hubs Index', 'A complete index directory of all financial calculators, category pages, blog articles, and programmatic finance pages on Money Metric Hubs.', 'basic', sitemapContent);

// PREFERENCES
const preferencesContent = `
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-6 animate-fade-in">
    <h1 class="font-display text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight">Global Preferences & settings</h1>
    <p class="text-slate-500 dark:text-slate-400 text-sm">Customize your Money Metric Hubs experience. These parameters are stored entirely in your browser log and are never synchronized to our servers.</p>
    
    <div class="p-6 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl space-y-4">
      <h3 class="font-bold text-slate-900 dark:text-white text-base">Regional Options</h3>
      <p class="text-xs text-slate-500 leading-relaxed">Choose your preferred currency and number formats.</p>
    </div>
  </div>
`;
generatePage('preferences', 'My Hub & Calculator Preferences | Money Metric Hubs', 'Customize your global preferences, view your history logs, and access your bookmarked calculators.', 'basic', preferencesContent);
generatePage('hub', 'My Personal Finance Hub | Money Metric Hubs', 'Your centralized personal finance dashboard containing saved calculators, history logs, and customization preferences.', 'basic', preferencesContent);

// COMPARE
const compareContent = `
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-6 animate-fade-in">
    <h1 class="font-display text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight">Side-by-Side Comparison Suite</h1>
    <p class="text-slate-500 dark:text-slate-400 text-sm">Compare multiple scenario results side-by-side. Save investment yields, loan interest schedules, or savings forecasts to see differences in total cost, payback speed, and compound velocity.</p>
    <div class="p-8 text-center bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl space-y-4">
      <p class="text-slate-500 text-sm">You have no scenarios currently loaded for comparison. Access any calculation page and click "Add to Compare" to initialize.</p>
    </div>
  </div>
`;
generatePage('compare', 'Compare Financial Scenarios | Money Metric Hubs', 'Add and compare multiple financial scenarios side-by-side. Save, analyze, and optimize your interest rates, investments, and loan structures.', 'basic', compareContent);

// DASHBOARD
const dashboardContent = `
  <div class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-8 animate-fade-in">
    <h1 class="font-display text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight">Google Search Console Performance Dashboard</h1>
    <p class="text-slate-500 dark:text-slate-400 text-sm">We publish our key metrics including total Google Search impressions, keyword click-through rates (CTR), and average rankings openly to maintain absolute user transparency.</p>
    <div class="p-8 text-center bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl">
      <p class="text-slate-500 text-xs sm:text-sm">Metrics are loaded client-side via Google APIs. Connect your regional webmaster properties to view real-time data panels.</p>
    </div>
  </div>
`;
generatePage('dashboard', 'Google Search Console Metrics | Money Metric Hubs', 'A real-time search engine optimization (SEO) transparency report and performance dashboard for Money Metric Hubs.', 'basic', dashboardContent);
generatePage('search-console', 'Google Search Console Metrics | Money Metric Hubs', 'A real-time search engine optimization (SEO) transparency report and performance dashboard for Money Metric Hubs.', 'basic', dashboardContent);

console.log('--- ALL PAGES SUCCESSFULY PRERENDERED ---');
